name: Sync Repo

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: arunnalla/.github/.github/workflows/sync-repos.yml@main
    with:
      name: static
    secrets:
      gitlabToken: ${{ secrets.GITLAB_TOKEN }}
